// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rjchien728/short-url/internal/pkg/snowflake (interfaces: IDGenerator)
//
// Generated by this command:
//
//	mockgen -destination=../../../internal/mock/mock_snowflake.go -package=mock github.com/rjchien728/short-url/internal/pkg/snowflake IDGenerator
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIDGenerator is a mock of IDGenerator interface.
type MockIDGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockIDGeneratorMockRecorder
	isgomock struct{}
}

// MockIDGeneratorMockRecorder is the mock recorder for MockIDGenerator.
type MockIDGeneratorMockRecorder struct {
	mock *MockIDGenerator
}

// NewMockIDGenerator creates a new mock instance.
func NewMockIDGenerator(ctrl *gomock.Controller) *MockIDGenerator {
	mock := &MockIDGenerator{ctrl: ctrl}
	mock.recorder = &MockIDGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDGenerator) EXPECT() *MockIDGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockIDGenerator) Generate() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockIDGeneratorMockRecorder) Generate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockIDGenerator)(nil).Generate))
}

// ShortCode mocks base method.
func (m *MockIDGenerator) ShortCode(id int64) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShortCode", id)
	ret0, _ := ret[0].(string)
	return ret0
}

// ShortCode indicates an expected call of ShortCode.
func (mr *MockIDGeneratorMockRecorder) ShortCode(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShortCode", reflect.TypeOf((*MockIDGenerator)(nil).ShortCode), id)
}
