// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rjchien728/short-url/internal/domain/gateway (interfaces: OGFetcher)
//
// Generated by this command:
//
//	mockgen -destination=../../mock/mock_gateway.go -package=mock github.com/rjchien728/short-url/internal/domain/gateway OGFetcher
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/rjchien728/short-url/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockOGFetcher is a mock of OGFetcher interface.
type MockOGFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockOGFetcherMockRecorder
	isgomock struct{}
}

// MockOGFetcherMockRecorder is the mock recorder for MockOGFetcher.
type MockOGFetcherMockRecorder struct {
	mock *MockOGFetcher
}

// NewMockOGFetcher creates a new mock instance.
func NewMockOGFetcher(ctrl *gomock.Controller) *MockOGFetcher {
	mock := &MockOGFetcher{ctrl: ctrl}
	mock.recorder = &MockOGFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOGFetcher) EXPECT() *MockOGFetcherMockRecorder {
	return m.recorder
}

// Fetch mocks base method.
func (m *MockOGFetcher) Fetch(ctx context.Context, url string) (*entity.OGMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", ctx, url)
	ret0, _ := ret[0].(*entity.OGMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fetch indicates an expected call of Fetch.
func (mr *MockOGFetcherMockRecorder) Fetch(ctx, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockOGFetcher)(nil).Fetch), ctx, url)
}
