// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rjchien728/short-url/internal/domain/repository (interfaces: ShortURLRepository,ClickLogRepository,URLCache,EventPublisher)
//
// Generated by this command:
//
//	mockgen -destination=../../mock/mock_repository.go -package=mock github.com/rjchien728/short-url/internal/domain/repository ShortURLRepository,ClickLogRepository,URLCache,EventPublisher
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/rjchien728/short-url/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockShortURLRepository is a mock of ShortURLRepository interface.
type MockShortURLRepository struct {
	ctrl     *gomock.Controller
	recorder *MockShortURLRepositoryMockRecorder
	isgomock struct{}
}

// MockShortURLRepositoryMockRecorder is the mock recorder for MockShortURLRepository.
type MockShortURLRepositoryMockRecorder struct {
	mock *MockShortURLRepository
}

// NewMockShortURLRepository creates a new mock instance.
func NewMockShortURLRepository(ctrl *gomock.Controller) *MockShortURLRepository {
	mock := &MockShortURLRepository{ctrl: ctrl}
	mock.recorder = &MockShortURLRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShortURLRepository) EXPECT() *MockShortURLRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockShortURLRepository) Create(ctx context.Context, url *entity.ShortURL) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, url)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockShortURLRepositoryMockRecorder) Create(ctx, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockShortURLRepository)(nil).Create), ctx, url)
}

// FindByShortCode mocks base method.
func (m *MockShortURLRepository) FindByShortCode(ctx context.Context, shortCode string) (*entity.ShortURL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByShortCode", ctx, shortCode)
	ret0, _ := ret[0].(*entity.ShortURL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByShortCode indicates an expected call of FindByShortCode.
func (mr *MockShortURLRepositoryMockRecorder) FindByShortCode(ctx, shortCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByShortCode", reflect.TypeOf((*MockShortURLRepository)(nil).FindByShortCode), ctx, shortCode)
}

// UpdateOGMetadata mocks base method.
func (m *MockShortURLRepository) UpdateOGMetadata(ctx context.Context, id int64, metadata *entity.OGMetadata) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOGMetadata", ctx, id, metadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOGMetadata indicates an expected call of UpdateOGMetadata.
func (mr *MockShortURLRepositoryMockRecorder) UpdateOGMetadata(ctx, id, metadata any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOGMetadata", reflect.TypeOf((*MockShortURLRepository)(nil).UpdateOGMetadata), ctx, id, metadata)
}

// MockClickLogRepository is a mock of ClickLogRepository interface.
type MockClickLogRepository struct {
	ctrl     *gomock.Controller
	recorder *MockClickLogRepositoryMockRecorder
	isgomock struct{}
}

// MockClickLogRepositoryMockRecorder is the mock recorder for MockClickLogRepository.
type MockClickLogRepositoryMockRecorder struct {
	mock *MockClickLogRepository
}

// NewMockClickLogRepository creates a new mock instance.
func NewMockClickLogRepository(ctrl *gomock.Controller) *MockClickLogRepository {
	mock := &MockClickLogRepository{ctrl: ctrl}
	mock.recorder = &MockClickLogRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClickLogRepository) EXPECT() *MockClickLogRepositoryMockRecorder {
	return m.recorder
}

// BatchCreate mocks base method.
func (m *MockClickLogRepository) BatchCreate(ctx context.Context, logs []*entity.ClickLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreate", ctx, logs)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchCreate indicates an expected call of BatchCreate.
func (mr *MockClickLogRepositoryMockRecorder) BatchCreate(ctx, logs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreate", reflect.TypeOf((*MockClickLogRepository)(nil).BatchCreate), ctx, logs)
}

// MockURLCache is a mock of URLCache interface.
type MockURLCache struct {
	ctrl     *gomock.Controller
	recorder *MockURLCacheMockRecorder
	isgomock struct{}
}

// MockURLCacheMockRecorder is the mock recorder for MockURLCache.
type MockURLCacheMockRecorder struct {
	mock *MockURLCache
}

// NewMockURLCache creates a new mock instance.
func NewMockURLCache(ctrl *gomock.Controller) *MockURLCache {
	mock := &MockURLCache{ctrl: ctrl}
	mock.recorder = &MockURLCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLCache) EXPECT() *MockURLCacheMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockURLCache) Delete(ctx context.Context, shortCode string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, shortCode)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockURLCacheMockRecorder) Delete(ctx, shortCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockURLCache)(nil).Delete), ctx, shortCode)
}

// Get mocks base method.
func (m *MockURLCache) Get(ctx context.Context, shortCode string) (*entity.ShortURL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, shortCode)
	ret0, _ := ret[0].(*entity.ShortURL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockURLCacheMockRecorder) Get(ctx, shortCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockURLCache)(nil).Get), ctx, shortCode)
}

// Set mocks base method.
func (m *MockURLCache) Set(ctx context.Context, shortCode string, url *entity.ShortURL, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, shortCode, url, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockURLCacheMockRecorder) Set(ctx, shortCode, url, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockURLCache)(nil).Set), ctx, shortCode, url, ttl)
}

// SetNotFound mocks base method.
func (m *MockURLCache) SetNotFound(ctx context.Context, shortCode string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNotFound", ctx, shortCode)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetNotFound indicates an expected call of SetNotFound.
func (mr *MockURLCacheMockRecorder) SetNotFound(ctx, shortCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNotFound", reflect.TypeOf((*MockURLCache)(nil).SetNotFound), ctx, shortCode)
}

// MockEventPublisher is a mock of EventPublisher interface.
type MockEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockEventPublisherMockRecorder
	isgomock struct{}
}

// MockEventPublisherMockRecorder is the mock recorder for MockEventPublisher.
type MockEventPublisherMockRecorder struct {
	mock *MockEventPublisher
}

// NewMockEventPublisher creates a new mock instance.
func NewMockEventPublisher(ctrl *gomock.Controller) *MockEventPublisher {
	mock := &MockEventPublisher{ctrl: ctrl}
	mock.recorder = &MockEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventPublisher) EXPECT() *MockEventPublisherMockRecorder {
	return m.recorder
}

// PublishClickEvent mocks base method.
func (m *MockEventPublisher) PublishClickEvent(ctx context.Context, event *entity.ClickLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishClickEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishClickEvent indicates an expected call of PublishClickEvent.
func (mr *MockEventPublisherMockRecorder) PublishClickEvent(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishClickEvent", reflect.TypeOf((*MockEventPublisher)(nil).PublishClickEvent), ctx, event)
}

// PublishOGFetchTask mocks base method.
func (m *MockEventPublisher) PublishOGFetchTask(ctx context.Context, task *entity.OGFetchTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishOGFetchTask", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishOGFetchTask indicates an expected call of PublishOGFetchTask.
func (mr *MockEventPublisherMockRecorder) PublishOGFetchTask(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishOGFetchTask", reflect.TypeOf((*MockEventPublisher)(nil).PublishOGFetchTask), ctx, task)
}
