// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rjchien728/short-url/internal/domain/service (interfaces: OGWorkerService,ClickWorkerService)
//
// Generated by this command:
//
//	mockgen -destination=../../mock/mock_worker_service.go -package=mock github.com/rjchien728/short-url/internal/domain/service OGWorkerService,ClickWorkerService
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/rjchien728/short-url/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockOGWorkerService is a mock of OGWorkerService interface.
type MockOGWorkerService struct {
	ctrl     *gomock.Controller
	recorder *MockOGWorkerServiceMockRecorder
	isgomock struct{}
}

// MockOGWorkerServiceMockRecorder is the mock recorder for MockOGWorkerService.
type MockOGWorkerServiceMockRecorder struct {
	mock *MockOGWorkerService
}

// NewMockOGWorkerService creates a new mock instance.
func NewMockOGWorkerService(ctrl *gomock.Controller) *MockOGWorkerService {
	mock := &MockOGWorkerService{ctrl: ctrl}
	mock.recorder = &MockOGWorkerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOGWorkerService) EXPECT() *MockOGWorkerServiceMockRecorder {
	return m.recorder
}

// ProcessTask mocks base method.
func (m *MockOGWorkerService) ProcessTask(ctx context.Context, task *entity.OGFetchTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessTask", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessTask indicates an expected call of ProcessTask.
func (mr *MockOGWorkerServiceMockRecorder) ProcessTask(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessTask", reflect.TypeOf((*MockOGWorkerService)(nil).ProcessTask), ctx, task)
}

// MockClickWorkerService is a mock of ClickWorkerService interface.
type MockClickWorkerService struct {
	ctrl     *gomock.Controller
	recorder *MockClickWorkerServiceMockRecorder
	isgomock struct{}
}

// MockClickWorkerServiceMockRecorder is the mock recorder for MockClickWorkerService.
type MockClickWorkerServiceMockRecorder struct {
	mock *MockClickWorkerService
}

// NewMockClickWorkerService creates a new mock instance.
func NewMockClickWorkerService(ctrl *gomock.Controller) *MockClickWorkerService {
	mock := &MockClickWorkerService{ctrl: ctrl}
	mock.recorder = &MockClickWorkerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClickWorkerService) EXPECT() *MockClickWorkerServiceMockRecorder {
	return m.recorder
}

// ProcessBatch mocks base method.
func (m *MockClickWorkerService) ProcessBatch(ctx context.Context, logs []*entity.ClickLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessBatch", ctx, logs)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessBatch indicates an expected call of ProcessBatch.
func (mr *MockClickWorkerServiceMockRecorder) ProcessBatch(ctx, logs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessBatch", reflect.TypeOf((*MockClickWorkerService)(nil).ProcessBatch), ctx, logs)
}
