// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rjchien728/short-url/internal/domain/service (interfaces: URLService,RedirectService)
//
// Generated by this command:
//
//	mockgen -destination=../../mock/mock_service.go -package=mock github.com/rjchien728/short-url/internal/domain/service URLService,RedirectService
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/rjchien728/short-url/internal/domain/entity"
	service "github.com/rjchien728/short-url/internal/domain/service"
	gomock "go.uber.org/mock/gomock"
)

// MockURLService is a mock of URLService interface.
type MockURLService struct {
	ctrl     *gomock.Controller
	recorder *MockURLServiceMockRecorder
	isgomock struct{}
}

// MockURLServiceMockRecorder is the mock recorder for MockURLService.
type MockURLServiceMockRecorder struct {
	mock *MockURLService
}

// NewMockURLService creates a new mock instance.
func NewMockURLService(ctrl *gomock.Controller) *MockURLService {
	mock := &MockURLService{ctrl: ctrl}
	mock.recorder = &MockURLServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLService) EXPECT() *MockURLServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockURLService) Create(ctx context.Context, req service.CreateURLRequest) (*entity.ShortURL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*entity.ShortURL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockURLServiceMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockURLService)(nil).Create), ctx, req)
}

// MockRedirectService is a mock of RedirectService interface.
type MockRedirectService struct {
	ctrl     *gomock.Controller
	recorder *MockRedirectServiceMockRecorder
	isgomock struct{}
}

// MockRedirectServiceMockRecorder is the mock recorder for MockRedirectService.
type MockRedirectServiceMockRecorder struct {
	mock *MockRedirectService
}

// NewMockRedirectService creates a new mock instance.
func NewMockRedirectService(ctrl *gomock.Controller) *MockRedirectService {
	mock := &MockRedirectService{ctrl: ctrl}
	mock.recorder = &MockRedirectServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedirectService) EXPECT() *MockRedirectServiceMockRecorder {
	return m.recorder
}

// RecordClick mocks base method.
func (m *MockRedirectService) RecordClick(ctx context.Context, log *entity.ClickLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordClick", ctx, log)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordClick indicates an expected call of RecordClick.
func (mr *MockRedirectServiceMockRecorder) RecordClick(ctx, log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordClick", reflect.TypeOf((*MockRedirectService)(nil).RecordClick), ctx, log)
}

// Resolve mocks base method.
func (m *MockRedirectService) Resolve(ctx context.Context, shortCode string) (*entity.ShortURL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx, shortCode)
	ret0, _ := ret[0].(*entity.ShortURL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockRedirectServiceMockRecorder) Resolve(ctx, shortCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockRedirectService)(nil).Resolve), ctx, shortCode)
}
