// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rjchien728/short-url/internal/pkg/geoip (interfaces: Resolver)
//
// Generated by this command:
//
//	mockgen -destination=../../mock/mock_geoip.go -package=mock github.com/rjchien728/short-url/internal/pkg/geoip Resolver
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGeoIPResolver is a mock of geoip.Resolver interface.
type MockGeoIPResolver struct {
	ctrl     *gomock.Controller
	recorder *MockGeoIPResolverMockRecorder
	isgomock struct{}
}

// MockGeoIPResolverMockRecorder is the mock recorder for MockGeoIPResolver.
type MockGeoIPResolverMockRecorder struct {
	mock *MockGeoIPResolver
}

// NewMockGeoIPResolver creates a new mock instance.
func NewMockGeoIPResolver(ctrl *gomock.Controller) *MockGeoIPResolver {
	mock := &MockGeoIPResolver{ctrl: ctrl}
	mock.recorder = &MockGeoIPResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGeoIPResolver) EXPECT() *MockGeoIPResolverMockRecorder {
	return m.recorder
}

// LookupCountry mocks base method.
func (m *MockGeoIPResolver) LookupCountry(ip string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupCountry", ip)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookupCountry indicates an expected call of LookupCountry.
func (mr *MockGeoIPResolverMockRecorder) LookupCountry(ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupCountry", reflect.TypeOf((*MockGeoIPResolver)(nil).LookupCountry), ip)
}
